//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaires
    {
        public Commentaires()
        {
            this.Commentaires1 = new HashSet<Commentaires>();
        }
    
        public int idComment { get; set; }
        public Nullable<int> idParent { get; set; }
        public string idAuteur { get; set; }
        public int idProduit { get; set; }
        public System.DateTime datePoste { get; set; }
        public string texte { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Commentaires> Commentaires1 { get; set; }
        public virtual Commentaires Commentaires2 { get; set; }
        public virtual Produits Produits { get; set; }
    }
}
