//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pays
    {
        public Pays()
        {
            this.Region = new HashSet<Region>();
        }
    
        public int IdPays { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<Region> Region { get; set; }
    }
}
