//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promos
    {
        public int IdPromo { get; set; }
        public Nullable<int> IdProduit { get; set; }
        public int Promo { get; set; }
        public System.DateTime DateDeb { get; set; }
        public System.DateTime DateFin { get; set; }
    
        public virtual Produits Produits { get; set; }
    }
}
