//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Ville = new HashSet<Ville>();
        }
    
        public int IdRegion { get; set; }
        public Nullable<int> IdPays { get; set; }
        public string Libelle { get; set; }
    
        public virtual Pays Pays { get; set; }
        public virtual ICollection<Ville> Ville { get; set; }
    }
}
